require 'nokogiri'
require 'simplecov'

class SimpleCov::Formatter::CoberturaFormatter
  RESULT_FILE_NAME = 'coverage.xml'
  DTD_URL = 'http://cobertura.sourceforge.net/xml/coverage-04.dtd'

  def format(result)
    xml = result_to_xml result

    result_path = File.join( SimpleCov.coverage_path, RESULT_FILE_NAME )
    File.write(result_path, xml)
    puts "Coverage report generated for #{result.command_name} to #{result_path}"
    xml
  end

  private
  def result_to_xml(result)
    doc = Nokogiri::XML::Document.new
    doc.root = Nokogiri::XML::Node.new('coverage', doc)
    coverage = doc.root

    set_coverage_attributes(coverage, result)

    coverage << sources = Nokogiri::XML::Node.new('sources', doc)
    sources << source = Nokogiri::XML::Node.new('source', doc)
    source << SimpleCov.root

    coverage << packages = Nokogiri::XML::Node.new('packages', doc)
    packages << package = Nokogiri::XML::Node.new('package', doc)
    set_package_attributes(package, result)

    package << classes = Nokogiri::XML::Node.new('classes', doc)

    result.files.each do |file|
      classes << class_ = Nokogiri::XML::Node.new('class', doc)
      set_class_attributes(class_, file)

      class_ << Nokogiri::XML::Node.new('methods', doc)
      class_ << lines = Nokogiri::XML::Node.new('lines', doc)

      file.lines.each do |file_line|
        if file_line.covered? || file_line.missed?
          lines << line = Nokogiri::XML::Node.new('line', doc)
          set_line_attributes(line, file_line)
        end
      end
    end

    set_xml_head(doc.to_s)
  end

  def set_coverage_attributes(coverage, result)
    coverage['line-rate'] = (result.covered_percent/100).round(2).to_s
    coverage['branch-rate'] = '0'
    coverage['lines-covered'] = result.covered_lines.to_s
    coverage['lines-valid'] = (result.covered_lines + result.missed_lines).to_s
    coverage['branches-covered'] = '0'
    coverage['branches-valid'] = '0'
    coverage['branch-rate'] = '0'
    coverage['complexity'] = '0'
    coverage['version'] = '0'
    coverage['timestamp'] = Time.now.to_i.to_s
  end

  def set_package_attributes(package, result)
    package['name'] = 'simplecov-cobertura'
    package['line-rate'] = (result.covered_percent/100).round(2).to_s
    package['branch-rate'] = '0'
    package['complexity'] = '0'
  end

  def set_class_attributes(class_, file)
    filename = file.filename
    path = filename[SimpleCov.root.length+1..-1]
    class_['name'] = File.basename(filename, '.*')
    class_['filename'] = path
    class_['line-rate'] = (file.covered_percent/100).round(2).to_s
    class_['branch-rate'] = '0'
    class_['complexity'] = '0'
  end

  def set_line_attributes(line, file_line)
    line['number'] = file_line.line_number.to_s
    line['branch'] = 'false'
    line['hits'] = file_line.coverage.to_s
  end

  def set_xml_head(xml)
    lines = xml.split("\n")
    lines.insert(1, "<!DOCTYPE coverage SYSTEM \"#{DTD_URL}\">")
    lines.insert(2, '<!-- Generated by simplecov-cobertura -->')
    lines.join("\n")
  end
end
